export enum Subjects {
  PUSERCREATED = "events.user.created",
  SUSERCREATED = "user.created",
  PBOOKCREATED = "events.book.created",
  SBOOKCREATED = "book.created",
  PQBOOKCREATED = "events.qbook.created",
  SQBOOKCREATED = "qbook.created",
  PCBOOKCREATED = "events.cbook.created",
  SCBOOKCREATED = "cbook.created",
  PCOMMENTCREATED = "events.comment.created",
  SCOMMENTCREATED = "comment.created",
  PREPLYCREATED = "events.reply.created",
  SREPLYCREATED = "reply.created",
  PCOMMENTUPDATED = "events.comment.update",
  SCOMMENTUPDATED = "comment.update",
  PREPLYUPDATED = "events.reply.update",
  SREPLYUPDATED = "reply.update",
  PBOOKUPDATED = "events.book.updated",
  SBOOKUPDATED = "book.updated",
  PQBOOKUPDATED = "events.qbook.updated",
  SQBOOKUPDATED = "qbook.updated",
  PCBOOKUPDATED = "events.cbook.updated",
  SCBOOKUPDATED = "cbook.updated",
  PEUSERCREATED = "events.euser.created",
  SEUSERCREATED = "euser.created",
}
