export enum Subjects {
  PUSERCREATED = "events.user.created",
  SUSERCREATED = "user.created",
  PBOOKCREATED = "events.book.created",
  SBOOKCREATED = "book.created",
  PQBOOKCREATED = "events.qbook.created",
  SQBOOKCREATED = "qbook.created",
  PEBOOKCREATED = "events.ebook.created",
  SEBOOKCREATED = "ebook.created",
  PCOMMENTCREATED = "events.comment.created",
  SCOMMENTCREATED = "comment.created",
  PREPLYCREATED = "events.reply.created",
  SREPLYCREATED = "reply.created",
  PCOMMENTUPDATED = "events.comment.update",
  SCOMMENTUPDATED = "comment.update",
  PREPLYUPDATED = "events.reply.update",
  SREPLYUPDATED = "reply.update",
}
